export const GET_VESSEL_DETAILS = "GET_VESSEL_DETAILS";
export const GET_BUZIOS_WEATHER = "GET_BUZIOS_WEATHER";
export const GET_PRATICAGEM = "GET_PRATICAGEM";
export const GET_DECOLAGENS = "GET_DECOLAGENS";
export const GET_VOOS_BUZIOS = "GET_VOOS_BUZIOS";
export const GET_ERROR = "GET_ERROR";
